Add multinode.yml workflow
stackhpc/stackhpc-openstack-gh-workflows pull request #1
Opened 2024-07-25 11:33 UTC by markgoddard

- **Add CODEOWNERS file**
- **Add a reusable GitHub workflow to deploy a multinode test cluster**
- **Add multinode.yml workflow**

2024-08-08 09:25 UTC, Alex-Welsh requested changes

2024-08-08 09:25 UTC, Alex-Welsh commented on .github/workflows/multinode.yml
> +        description: User for terraform to access the all-in-one VM
```suggestion
        description: User for terraform to access the Multinode VMs
```

2024-08-08 09:25 UTC, Alex-Welsh commented on .github/workflows/multinode.yml
> +      stackhpc_kayobe_config_version:
required?

2024-08-08 09:25 UTC, Alex-Welsh commented on .github/workflows/multinode.yml
> +          vxlan_vni: 53299
Would be nice if this was randomised/customisable, perhaps in some bounded range for "CI multinodes"

2024-08-08 09:25 UTC, Alex-Welsh commented on .github/workflows/multinode.yml
> +        uses: hashicorp/setup-terraform@v2
```suggestion
        uses: hashicorp/setup-terraform@v3
```

2024-08-08 09:25 UTC, Alex-Welsh commented on .github/workflows/multinode.yml
> +      break_on:
might be better as a choice rather than a string

2024-08-08 09:25 UTC, Alex-Welsh commented on .github/workflows/multinode.yml
> +      - name: Break on failure
Also worth having break on success/always?

2024-08-08 09:38 UTC, Alex-Welsh commented on .github/workflows/multinode.yml
> +      break_on:
I've now seen that the workflow calling this one has a choice, which makes sense

2024-08-20 11:53 UTC, markgoddard commented on .github/workflows/multinode.yml
> +      stackhpc_kayobe_config_version:
+1

2024-08-20 11:53 UTC, markgoddard commented on .github/workflows/multinode.yml
> +        uses: hashicorp/setup-terraform@v2
It doesn't work for some reason. Perhaps the github runner container image?

2024-08-20 11:53 UTC, markgoddard commented on .github/workflows/multinode.yml
> +          vxlan_vni: 53299
Oops, yes this should not be constant.

2024-08-20 11:53 UTC, markgoddard commented on .github/workflows/multinode.yml
> +      - name: Break on failure
+1

2024-08-20 16:11 UTC, Alex-Welsh approved these changes, later dismissed

2024-08-20 16:11 UTC, Alex-Welsh commented on .github/workflows/multinode.yml
> +        id: tf_apply
nit: unused

2024-08-20 16:24 UTC, merged